// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA8NG1qGpLGgHovMLefKeC7PqWgM2eOt0',
    appId: '1:600688007911:web:1641e98a4d9e7662ad6042',
    messagingSenderId: '600688007911',
    projectId: 'wellth-app',
    authDomain: 'wellth-app.firebaseapp.com',
    storageBucket: 'wellth-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3oW9h0BiNr062_Il1caBohG5HsWATyKQ',
    appId: '1:600688007911:android:e7c8351e016ca491ad6042',
    messagingSenderId: '600688007911',
    projectId: 'wellth-app',
    storageBucket: 'wellth-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt126tdYin9fFzK7rl24b7n7ATOzy6ue8',
    appId: '1:600688007911:ios:c7ae6da733b31133ad6042',
    messagingSenderId: '600688007911',
    projectId: 'wellth-app',
    storageBucket: 'wellth-app.firebasestorage.app',
    iosBundleId: 'com.example.wellthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt126tdYin9fFzK7rl24b7n7ATOzy6ue8',
    appId: '1:600688007911:ios:c7ae6da733b31133ad6042',
    messagingSenderId: '600688007911',
    projectId: 'wellth-app',
    storageBucket: 'wellth-app.firebasestorage.app',
    iosBundleId: 'com.example.wellthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA8NG1qGpLGgHovMLefKeC7PqWgM2eOt0',
    appId: '1:600688007911:web:cf9339038dda1946ad6042',
    messagingSenderId: '600688007911',
    projectId: 'wellth-app',
    authDomain: 'wellth-app.firebaseapp.com',
    storageBucket: 'wellth-app.firebasestorage.app',
  );
}
